CREATE TABLE Clientes
(
ID NUMERIC(8) UNIQUE,
NOME CHAR(60),
MORADA CHAR(30),
CONTACTO NUMERIC(12),
EMPRESA_ASSOCIADA NUMERIC(8),
DATA CHAR(25),
PESO NUMERIC(7),
PRECO_TOTAL NUMERIC(30),
PRIMARY KEY (ID)
);
